### ISSUE TITLE
Firefox reported SEC_ERROR_REUSED_ISSUER_AND_SERIAL for MITM

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly#872]
## Description of the bug
When using hoverfly to proxy HTTPS requests in Firefox, some requests are blocked randomly due to security error `SEC_ERROR_REUSED_ISSUER_AND_SERIAL` 

## Steps to reproduce the issue
1. Start hoverfly in capture mode
2. Add Hoverfly cert to the Certificate Authorities in the Certificate Manager in Firefox
3. Set Firefox to use hoverfly (localhost:8500) as HTTPS proxy
4. Browse to any HTTPS website

### Observed result
**If possible, add screenshots to help explain your problem**
![image](https://user-images.githubusercontent.com/7671879/61643007-e72d7300-ac99-11e9-94d5-4b60aa922ac4.png)

### Expected result
All HTTPS requests should be proxied by hoverfly, and no security error should be reported.

## Additional relevant information
1. Hoverfly version: v1.1.0
2. Anything that might help us to diagnose the problem
- This problem is not observed when using Google Chrome. 
- It may be related to this issue: https://github.com/elazarl/goproxy/issues/311

**Comment by ns3777k** [comment]
@tommysitu this should be fixed as well as #898 . can you double check?

**Comment by tommysitu** [comment]
Yeah, checking

**Comment by tommysitu** [comment]
😞 it doesn't solve this error `SEC_ERROR_REUSED_ISSUER_AND_SERIAL`, it's not to do with the weak key.

**Comment by ns3777k** [comment]
Strange. that worked for me. I'll give it a try later

**Comment by tommysitu** [comment]
It's not blocking all the https calls, only some of the calls if you looking at the network tab in Firefox.

**Comment by ns3777k** [comment]
I moved a commit from goproxy upstream that fixes this. I'll bump the goproxy dependency once merged.

**Comment by tommysitu** [comment]
Your fix works like a charm! @ns3777k Another ssl issue sorted 👍
